import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { rankProjects } from "@/lib/ranking";
import { explainTopRanked } from "@/lib/llm";
import { Button } from "@/components/ui/button";
import type { BtoProject, CoupleMember, Location, Preferences } from "@/types";

export default async function ExplainPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const { data: membership } = await supabase
    .from("couple_members")
    .select("couple_id")
    .eq("user_id", user.id)
    .limit(1)
    .maybeSingle();
  if (!membership) redirect("/onboarding");

  const coupleId = membership.couple_id;

  const [{ data: members }, { data: locations }, { data: preferences }, { data: projects }] = await Promise.all([
    supabase.from("couple_members").select("*").eq("couple_id", coupleId),
    supabase.from("locations").select("*").eq("couple_id", coupleId),
    supabase.from("preferences").select("*").eq("couple_id", coupleId),
    supabase.from("bto_projects").select("*"),
  ]);

  const ms = (members ?? []) as CoupleMember[];
  const ls = (locations ?? []) as Location[];
  const ps = (preferences ?? []) as Preferences[];
  const projs = (projects ?? []) as BtoProject[];

  const partners = ms.map((m) => ({
    userId: m.user_id,
    displayName: m.display_name,
    preferences: ps.find((p) => p.user_id === m.user_id)!,
    locations: ls.filter((l) => l.user_id === m.user_id),
  })).filter((p) => p.preferences); // guard: skip partners without preferences yet

  const ranked = rankProjects(projs, partners);
  const top5 = ranked.slice(0, 5);

  let rationales: Record<string, string> = {};
  let llmError: string | null = null;

  if (top5.length > 0 && process.env.ANTHROPIC_API_KEY) {
    try {
      rationales = await explainTopRanked(top5, partners);

      // Cache to scores table
      const upserts = top5.map((p) => ({
        couple_id: coupleId,
        project_id: p.id,
        score: p.score,
        breakdown: p.breakdown,
        llm_reasoning: rationales[p.project_name] ?? null,
      }));
      await supabase.from("scores").upsert(upserts);
    } catch (e) {
      llmError = e instanceof Error ? e.message : "LLM generation failed";
    }
  } else if (!process.env.ANTHROPIC_API_KEY) {
    llmError = "ANTHROPIC_API_KEY not configured";
  }

  return (
    <main className="px-6 md:px-10 py-10 max-w-3xl mx-auto">
      <p className="eyebrow mb-4">AI Rationale</p>
      <h1 className="font-display text-4xl tracking-tightest mb-3 text-balance">
        Why your <span className="italic">top picks</span> ranked here.
      </h1>
      <p className="text-ink-soft mb-10 text-pretty">
        Generated by Claude using your actual preferences and locations.
      </p>

      {llmError && (
        <div className="border border-rust/30 bg-rust/5 p-4 mb-8">
          <p className="text-sm text-rust">{llmError}</p>
        </div>
      )}

      <div className="space-y-6">
        {top5.map((p, i) => (
          <article key={p.id} className="border border-ink/10 p-6">
            <div className="flex items-baseline justify-between mb-3">
              <div className="flex items-baseline gap-3">
                <span className="num text-clay">#{i + 1}</span>
                <h2 className="font-display text-2xl">{p.project_name}</h2>
              </div>
              <span className="num text-2xl">{p.score.toFixed(0)}</span>
            </div>
            <p className="text-sm text-ink-muted mb-4">
              {p.town} · {p.launch}
            </p>
            {rationales[p.project_name] ? (
              <p className="font-display italic text-lg leading-relaxed text-ink-soft text-pretty">
                "{rationales[p.project_name]}"
              </p>
            ) : (
              <p className="text-ink-muted italic">
                Rationale not generated yet.
              </p>
            )}
          </article>
        ))}
      </div>

      <div className="mt-12">
        <Button asChild variant="outline">
          <Link href="/app">← Back to rankings</Link>
        </Button>
      </div>
    </main>
  );
}
